// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

   static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQJsiBMhinlrbI30soamEh6Ua6miwFLGs',
    appId: '1:506520187763:web:afcb75c34cc668f6564b06',
    messagingSenderId: '506520187763',
    projectId: 'emergencyresponse-0xyvwt',
    authDomain: 'emergencyresponse-0xyvwt.firebaseapp.com',
    storageBucket: 'emergencyresponse-0xyvwt.firebasestorage.app',
    databaseURL: 'https://emergencyresponse-0xyvwt-default-rtdb.asia-southeast1.firebasedatabase.app/',
    measurementId: 'G-1ZQY3EJ6X1',
  
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQJsiBMhinlrbI30soamEh6Ua6miwFLGs',
    appId: '1:506520187763:web:afcb75c34cc668f6564b06',
    messagingSenderId: '506520187763',
    projectId: 'emergencyresponse-0xyvwt',
    storageBucket: 'emergencyresponse-0xyvwt.firebasestorage.app',
    databaseURL: 'https://emergencyresponse-0xyvwt-default-rtdb.asia-southeast1.firebasedatabase.app/',
    
  );
}
